branches:
  only:
    - gh-pages
language: node_js
node_js:
  - node
notifications:
  email:
    on_success: never
services:
  - docker
sudo: required

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash

script:
  - docker exec -it emscripten make

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  keep_history: true
  skip_cleanup: true
  on:
    branch: gh-pages
